const  challenges = [
    {
      id: "1",
      title: "Product Card Component",
      description: "Create a responsive product card with image, title, price, and add to cart button.",
      difficulty: "Easy",
      type: "Official",
      tags: ["HTML", "CSS", "Component"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: "2",
      title: "Navigation Bar",
      description: "Build a responsive navigation bar with dropdown menus and mobile toggle.",
      difficulty: "Medium",
      type: "Official",
      tags: ["HTML", "CSS", "JavaScript", "Responsive"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: "3",
      title: "E-commerce Product Page",
      description: "Create a complete product page with image gallery, reviews, and add to cart functionality.",
      difficulty: "Hard",
      type: "Official",
      tags: ["HTML", "CSS", "JavaScript", "Complex Layout"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: "4",
      title: "Testimonial Grid",
      description: "Build a responsive testimonial grid with different card sizes and layouts.",
      difficulty: "Easy",
      type: "Official",
      tags: ["HTML", "CSS", "Grid"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: "5",
      title: "Pricing Table",
      description: "Create a responsive pricing table with highlighted recommended plan.",
      difficulty: "Medium",
      type: "Official",
      tags: ["HTML", "CSS", "Pricing"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: "6",
      title: "Dashboard UI",
      description: "Build a complex dashboard interface with charts, tables, and sidebar navigation.",
      difficulty: "Hard",
      type: "Official",
      tags: ["HTML", "CSS", "JavaScript", "Dashboard"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: "7",
      title: "Login Form",
      description: "Create a stylish login form with validation and error states.",
      difficulty: "Easy",
      type: "Community",
      tags: ["HTML", "CSS", "Form"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: "8",
      title: "Todo App",
      description: "Build a functional todo app with add, edit, delete, and filter capabilities.",
      difficulty: "Medium",
      type: "Community",
      tags: ["HTML", "CSS", "JavaScript", "CRUD"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: "9",
      title: "E-commerce Checkout Flow",
      description: "Create a multi-step checkout process with form validation and order summary.",
      difficulty: "Hard",
      type: "Community",
      tags: ["HTML", "CSS", "JavaScript", "Forms", "Validation"],
      image: "/placeholder.svg?height=200&width=400",
    },
  ]
  
  export default challenges